# Enable the creation of pod security policy
podSecurityPolicy:
  enabled: false

# Create a specific service account
serviceAccount:
  create: true
  name: nginx-ingress

# Publish services on port HTTPS/443
# These services are exposed on the node with IP 192.168.111.110
controller:
  service:
    enableHttp: false
    externalIPs:
      - 192.168.111.110
