apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  capacity:
    storage: 20Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: wp
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /export/wp-vol
    server: 192.168.111.2

