apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: nginx-container
    image: smt.example.com:5000/docker.io/nginx:1.12.0
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: opensuse-container
    image: smt.example.com:5000/docker.io/opensuse/leap
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo 'Have a lot of fun!' > /pod-data/index.html"]

