# This pod mounts the nfs volume claim into /usr/share/nginx/html and
# serves a simple web page.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-web
spec:
  selector:
   matchLabels:
     app: nfs-web
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs-web
    spec:
      containers:
      - name: web
        image: smt.example.com:5000/docker.io/nginx:1.9.0
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
            - name: nfs-vol-01
              mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nfs-vol-01
        persistentVolumeClaim:
          claimName: nfs-vol-01
