kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
  name: tux
subjects:
  - kind: ServiceAccount
    name: tux
    namespace: default
roleRef:
  kind: Role
  name: 
  apiGroup: rbac.authorization.k8s.io
