apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: busybox
        image: smt.example.com:5000/docker.io/busybox
        command:
          - sh
          - -c
          - 'while true; do wget -q -O- http://php-apache.default.svc.cluster.local; done'

