apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: load-generator
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: load-generator
    spec:
      containers:
      - image: busybox
        name: busybox
        command:
          - sh
          - -c
          - 'while true; do wget -q -O- http://php-apache.default.svc.cluster.local; done'

